########################################################################################################################
##             ____________________  ________.___                           __                                        ##
##             \______   \______   \/  _____/|   | _______  __ ____   _____/  |_  ___________ ___.__.                 ##
##             |       _/|     ___/   \  ___|   |/    \  \/ // __ \ /    \   __\/  _ \_  __ <   |  |                  ##
##             |    |   \|    |   \    \_\  \   |   |  \   /\  ___/|   |  \  | (  <_> )  | \/\___  |                  ##
##             |____|_  /|____|    \______  /___|___|  /\_/  \___  >___|  /__|  \____/|__|   / ____|                  ##
##             \/                  \/         \/          \/     \/                   \/                              ##
########################################################################################################################
###############
#   By Neko   #
###############

enable: true

menu_command: menu # The command to access to the main menu.

#ItemsAdder item to display the menu button in inventories.
menu_button: _iainternal:icon_next_orange
left_arrow_button: _iainternal:icon_back_orange
equip_button: _iainternal:icon_next_orange
right_arrow_button: _iainternal:icon_right_blue
unlocked_item_button: _iainternal:icon_cancel
locked_item_button: _iainternal:icon_cancel

undefined_item: _iainternal:icon_cancel